version: '3'
services:
  appserver:
    build: .
    image: madsimo/team-a-frontend
    ports:
      - "8080:8080"
    network_mode: "host"


  appclient:
    build: .
    image: madsimo/team-a-backend
    ports:
      - "8090:8090"
    network_mode: "host"
